version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./public/downloads:/app/public/downloads:ro
    depends_on:
      - app
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./public/downloads:/app/public/downloads
    user: "1000:1000"
    restart: unless-stopped
    networks:
      - app_network

  cron:
    image: alpine
    command: >
      sh -c '
        apk add --no-cache curl &&
        echo "0 0 * * * curl -X GET http://app:3000/api/cron" > /etc/crontabs/root &&
        crond -f -l 2
      '
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
