services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app_network

  ytdlp:
    build:
      context: .
      dockerfile: ./ytdlp/Dockerfile
    volumes:
      - ./downloads:/downloads
    user: "1000:1000"
    environment:
      - TZ=UTC

networks:
  app_network:
    driver: bridge
